VirtoCommerce.InventoryModule.Data/Repositories/InventoryRepositoryImpl.cs
VirtoCommerce.InventoryModule.Web/JsonConverters/PolymorphicInventoryJsonConverter.cs
VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.js
VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.tpl.html
VirtoCommerce.InventoryModule.Web/Scripts/inventory.js
VirtoCommerce.InventoryModule.Web/Scripts/widgets/fulfillmentAddressesWidget.js

Added fulfillment type to knowtypes in PolymorphicInventoryJsonConverter.
Added metaform support to fulfillment details blade.

Added ability to extend FulfillmentCenter. Added ability to use metaforms in fulfillment detail blade.

---

VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterSearchService.cs
VirtoCommerce.InventoryModule.Data/Services/InventorySearchService.cs

Paged search ordering revision

---

VirtoCommerce.InventoryModule.Web/ExportImport/InventoryExportImport.cs

#27: Fixed exception on import of extended objects.

---

CommonAssemblyInfo.cs
VirtoCommerce.InventoryModule.Web/ExportImport/InventoryExportImport.cs
VirtoCommerce.InventoryModule.Web/module.manifest

Fixed error with FK violation on import.

Features 31 import inventory fk violation

---

src/VirtoCommerce.InventoryModule.Data/Model/InventoryEntity.cs
src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryDbContext.cs
src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryRepositoryImpl.cs

fix for https://virtocommerce.atlassian.net/browse/VP-596

fix inventory fulfillmetCenters query

---

VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterInventories.cs
VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterInventory.cs
VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterInventoryInfo.cs
VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterInventorySearchService.cs
VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterSearchService.cs
VirtoCommerce.InventoryModule.Data/Services/IFulfillmentCenterInventorySearchService.cs
VirtoCommerce.InventoryModule.Data/Services/InventorySearchService.cs
VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
VirtoCommerce.InventoryModule.Web/Content/css/inventory.css
VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs
VirtoCommerce.InventoryModule.Web/Localizations/en.VirtoCommerce.Inventory.json
VirtoCommerce.InventoryModule.Web/Module.cs
VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-fulfillmentcenters-list.js
VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-fulfillmentcenters-list.tpl.html
VirtoCommerce.InventoryModule.Web/Scripts/resources/fulfillments.js
VirtoCommerce.InventoryModule.Web/Scripts/resources/inventory.js
VirtoCommerce.InventoryModule.Web/VirtoCommerce.InventoryModule.Web.csproj
VirtoCommerce.InventoryModule.Web/module.manifest

UI for manage Fulfillment centers

Dev vp 730 a lot of ffc

---

VirtoCommerce.InventoryModule.Web/ExportImport/InventoryExportImport.cs

Returned InventoryInfo truly stream import, changed order of export to avoid error.

InventoryInfo stream import fix

---

VirtoCommerce.InventoryModule.sln
src/VirtoCommerce.InventoryModule.Core/Model/InventoryInfo.cs
src/VirtoCommerce.InventoryModule.Core/Model/Search/InventorySearchCriteria.cs
src/VirtoCommerce.InventoryModule.Core/Model/Search/ProductInventorySearchCriteria.cs
src/VirtoCommerce.InventoryModule.Core/ModuleConstants.cs
src/VirtoCommerce.InventoryModule.Core/Services/IInventorySearchService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IProductInventorySearchService.cs
src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/ExportImport/InventoryExportImport.cs
src/VirtoCommerce.InventoryModule.Data/Model/InventoryEntity.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventorySearchService.cs
src/VirtoCommerce.InventoryModule.Data/Services/ProductInventorySearchService.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs
src/VirtoCommerce.InventoryModule.Web/JsonConverters/PolymorphicInventoryJsonConverter.cs
src/VirtoCommerce.InventoryModule.Web/Localizations/en.VirtoCommerce.Inventory.json
src/VirtoCommerce.InventoryModule.Web/Module.cs
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.tpl.html
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-detail.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-fulfillmentcenters-list.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-fulfillmentcenters-list.tpl.html
src/VirtoCommerce.InventoryModule.Web/Scripts/resources/fulfillments.js
src/VirtoCommerce.InventoryModule.Web/Scripts/resources/inventory.js

This changes was moved
https://github.com/VirtoCommerce/vc-module-inventory/compare/286dc0592582a22600562740a7e64ecb948e2d34...757258f4189137bc6959677f917b45c0c30ac196

Actualization v3 with changes from v2

---

src/VirtoCommerce.InventoryModule.Data/Handlers/IndexInventoryChangedEventHandler.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/Localizations/en.VirtoCommerce.Inventory.json
src/VirtoCommerce.InventoryModule.Web/Module.cs
src/VirtoCommerce.InventoryModule.Web/VirtoCommerce.InventoryModule.Web.csproj

https://virtocommerce.atlassian.net/browse/VP-2401

Apply EventBasedIndexation setting value immediately #VP-2401

---

src/VirtoCommerce.InventoryModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/VP-3118

VP-3118: Fix logo

---

src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventoryServiceImpl.cs

A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
A clear and concise description of what you want to happen.
Describe the technical details of realization provided by you.
Add any other context or screenshots about the feature request here.

VP-5334: Call ClearCache before publish event

---

src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-fulfillmentcenters-list.js

Change items per page constant

VP-5841: Fix FFC lazy loading doesn't work

---

src/VirtoCommerce.InventoryModule.Web/Scripts/widgets/inventoryWidget.tpl.html

VP-6364 Add icons to widgets inside Product blade
Add icon to the widget

VP-6364: Add icons to widgets inside Product blade

---

src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-list.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-list.tpl.html
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-detail.js

VP-6366: Replace panel action icons

---

src/VirtoCommerce.InventoryModule.Web/Scripts/widgets/storeFulfillmentWidget.tpl.html

VP-6648: Add icons to widgets inside store settings blade

---

src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-list.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-detail.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-fulfillmentcenters-list.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/store-fulfillment-centers.js

VP-6864: Fix header icon

---

src/VirtoCommerce.InventoryModule.Core/ModuleConstants.cs
src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj

[Validation on settings input fields](https://virtocommerce.atlassian.net/browse/VP-6756)
User can enter negative digits in input fields where values should be positive 
Update platform dependency
Use suitable value type for input validation

VP-6756: Fix validation on settings input fields

---

src/VirtoCommerce.InventoryModule.Web/Scripts/directives/uiInventorySelector.js

fix for cannot save store after removing ffc in single ffc dropdown
https://virtocommerce.atlassian.net/browse/VP-7260

VP-7260 fix remove single fulfullment center

---

src/VirtoCommerce.InventoryModule.Web/Scripts/blades/store-fulfillment-centers.tpl.html
src/VirtoCommerce.InventoryModule.Web/Scripts/directives/uiInventorySelector.js
src/VirtoCommerce.InventoryModule.Web/Scripts/directives/uiInventorySelector.tpl.html

https://virtocommerce.atlassian.net/browse/PT-482

PT-689 inventory search paging fix

---

src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-207

VP-6823: GetConnectionString from ModuleId

---

src/VirtoCommerce.InventoryModule.Web/Scripts/widgets/fulfillmentAddressesWidget.js
src/VirtoCommerce.InventoryModule.Web/module.manifest

https://virtocommerce.atlassian.net/browse/PT-1897

PT-1899: Change address Region input to selector

---

.github/workflows/main.yml
src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IInventorySearchService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IInventoryService.cs
src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/ExportImport/InventoryExportImport.cs
src/VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterEntity.cs
src/VirtoCommerce.InventoryModule.Data/Model/InventoryEntity.cs
src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityChangesProvider.cs
src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityDocumentBuilder.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventorySearchService.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventoryServiceImpl.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs
src/VirtoCommerce.InventoryModule.Web/module.manifest

Implement generic CRUD service
https://virtocommerce.atlassian.net/browse/PT-2265

PT-2265: Rework inventory module to generic CRUD

---

src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/module.manifest

Extend Address with OuterId property
https://virtocommerce.atlassian.net/browse/PT-4060

PT-4060: Extend Address with OuterId property

---

src/VirtoCommerce.InventoryModule.Core/Services/IInventorySearchService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IInventoryService.cs
src/VirtoCommerce.InventoryModule.Data/ExportImport/InventoryExportImport.cs
src/VirtoCommerce.InventoryModule.Data/Model/InventoryEntity.cs
src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityChangesProvider.cs
src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityDocumentBuilder.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventorySearchService.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventoryServiceImpl.cs
src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs

The product quantity does not decrease in Stock
https://virtocommerce.atlassian.net/browse/PT-4511

PT-4511: Bug fix

---

src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityDocumentBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-4524

PT-4524: System re-index the product after changing quantity

---

.github/workflows/main.yml
.github/workflows/publish_nugets.yml
Directory.Build.props
src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryDbContext.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/VirtoCommerce.InventoryModule.Web.csproj
src/VirtoCommerce.InventoryModule.Web/module.manifest
tests/VirtoCommerce.InventoryModule.Tests/VirtoCommerce.InventoryModule.Tests.csproj

Bump .Net and EF up to 6
https://virtocommerce.atlassian.net/browse/PT-1956

PT-1956: Bump .Net and EF up to 6

---

src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/Handlers/IndexInventoryChangedEventHandler.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/VirtoCommerce.InventoryModule.Web.csproj
src/VirtoCommerce.InventoryModule.Web/module.manifest

Partial search index update support

PT-6527: Partial search index update support

---

src/VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterEntity.cs

Fix OuterId update
https://virtocommerce.atlassian.net/browse/PT-6396

PT-6396: Fix OuterId update

---

src/VirtoCommerce.InventoryModule.Web/Localizations/en.VirtoCommerce.Inventory.json

Corrected mistakes in the EN loc file and rewrote some phrases.

docs: Fix language in the EN loc file

---

src/VirtoCommerce.InventoryModule.Core/Model/FulfillmentCenter.cs
src/VirtoCommerce.InventoryModule.Data/Migrations/20220627121525_addFFCShortDescription.Designer.cs
src/VirtoCommerce.InventoryModule.Data/Migrations/20220627121525_addFFCShortDescription.cs
src/VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterEntity.cs
src/VirtoCommerce.InventoryModule.Web/Localizations/en.VirtoCommerce.Inventory.json
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.js
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.tpl.html
src/VirtoCommerce.InventoryModule.Web/module.manifest

Fulfillment center short description field
https://virtocommerce.atlassian.net/browse/PT-8007

PT-8007: Fulfillment center short description field

---

src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Data/ExportImport/InventoryExportImport.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterGeoService.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs
src/VirtoCommerce.InventoryModule.Web/Module.cs
tests/VirtoCommerce.InventoryModule.Tests/FulfillmentCenterGeoServiceTests.cs

Derive fulfillment center interfaces from generic ones

---

src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryDbContext.cs

Fix EF validation runtime warnings
https://virtocommerce.atlassian.net/browse/PT-9152

PT-9152: Fix EF validation runtime warnings

---

Directory.Build.props
src/VirtoCommerce.InventoryModule.Core/Model/FulfillmentCenter.cs
src/VirtoCommerce.InventoryModule.Core/Model/Search/FulfillmentCenterSearchCriteria.cs
src/VirtoCommerce.InventoryModule.Data/Migrations/20221026090608_AddOrganizationId.Designer.cs
src/VirtoCommerce.InventoryModule.Data/Migrations/20221026090608_AddOrganizationId.cs
src/VirtoCommerce.InventoryModule.Data/Model/FulfillmentCenterEntity.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-list.js
src/VirtoCommerce.InventoryModule.Web/module.manifest

VM-1075: outerId in fulfillment search

---

src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityDocumentBuilder.cs
src/VirtoCommerce.InventoryModule.Web/Scripts/inventory.js
src/VirtoCommerce.InventoryModule.Web/Scripts/widgets/inventoryWidget.js

feat: Add Product availability into Index document
feat: inventory widget availabe for all products' types
https://virtocommerce.atlassian.net/browse/PT-11722

PT-11722: Add Product availability into Index document

---

.editorconfig
Directory.Build.props
VirtoCommerce.InventoryModule.sln.DotSettings
src/VirtoCommerce.InventoryModule.Core/ModuleConstants.cs
src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data.MySql/VirtoCommerce.InventoryModule.Data.MySql.csproj
src/VirtoCommerce.InventoryModule.Data.PostgreSql/VirtoCommerce.InventoryModule.Data.PostgreSql.csproj
src/VirtoCommerce.InventoryModule.Data.SqlServer/VirtoCommerce.InventoryModule.Data.SqlServer.csproj
src/VirtoCommerce.InventoryModule.Data/ExportImport/InventoryExportImport.cs
src/VirtoCommerce.InventoryModule.Data/Handlers/IndexInventoryChangedEventHandler.cs
src/VirtoCommerce.InventoryModule.Data/Handlers/LogChangesChangedEventHandler.cs
src/VirtoCommerce.InventoryModule.Data/Repositories/IInventoryRepository.cs
src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryRepositoryImpl.cs
src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityDocumentBuilder.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterGeoService.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterSearchService.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Data/Services/InventoryServiceImpl.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs
src/VirtoCommerce.InventoryModule.Web/Module.cs
src/VirtoCommerce.InventoryModule.Web/VirtoCommerce.InventoryModule.Web.csproj
src/VirtoCommerce.InventoryModule.Web/module.manifest
tests/VirtoCommerce.InventoryModule.Tests/FulfillmentCenterGeoServiceTests.cs
tests/VirtoCommerce.InventoryModule.Tests/InventoryServiceImplUnitTests.cs
tests/VirtoCommerce.InventoryModule.Tests/VirtoCommerce.InventoryModule.Tests.csproj

https://virtocommerce.atlassian.net/browse/PT-10449

PT-10449: Update Crud and Search services

---

src/VirtoCommerce.InventoryModule.Data/Search/Indexing/ProductAvailabilityDocumentBuilder.cs

https://virtocommerce.atlassian.net/browse/PT-13034
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Inventory_3.403.0-pr-135-ba3e.zip

PT-13034: Implement IIndexSchemaBuilder

---

src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryDbContext.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/module.manifest

fix: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.
https://virtocommerce.atlassian.net/browse/PT-13179

PT-13179: DateTime values coming back from the SqlServer database always have a DateTimeKind of Unspecified.

---

src/VirtoCommerce.InventoryModule.Web/Scripts/blades/inventory-detail.tpl.html

feat: Improve UX on Inventory Detail by adding more space for input. 
fix: Fix changes input type from float to number.
https://virtocommerce.atlassian.net/browse/PT-14107
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Inventory_3.405.0-pr-137-8b42.zip

PT-14104: Improve UX on Inventory Detail

---

src/VirtoCommerce.InventoryModule.Web/Scripts/blades/fulfillment-center-detail.tpl.html

make widget container in FFC details wider
https://virtocommerce.atlassian.net/browse/VCST-1928
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Inventory_3.806.0-pr-142-39a7.zip

VCST-1928: make widget container in FFC details wider

---

src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs

feat: Added HttpPatch methods for FulfillmentCenter and InventoryInfo
https://virtocommerce.atlassian.net/browse/VCST-3182
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Inventory_3.809.0-pr-147-7f03.zip

VCST-3182: HttpPatch methods for FulfillmentCenter and InventoryInfo

---

src/VirtoCommerce.InventoryModule.Core/Model/FulfillmentCenter.cs
src/VirtoCommerce.InventoryModule.Core/Model/InventoryInfo.cs
src/VirtoCommerce.InventoryModule.Core/Services/IFulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Core/VirtoCommerce.InventoryModule.Core.csproj
src/VirtoCommerce.InventoryModule.Data.MySql/Migrations/20250520110319_AddIndexForOuterId.Designer.cs
src/VirtoCommerce.InventoryModule.Data.MySql/Migrations/20250520110319_AddIndexForOuterId.cs
src/VirtoCommerce.InventoryModule.Data.MySql/VirtoCommerce.InventoryModule.Data.MySql.csproj
src/VirtoCommerce.InventoryModule.Data.PostgreSql/Migrations/20250520110310_AddIndexForOuterId.Designer.cs
src/VirtoCommerce.InventoryModule.Data.PostgreSql/Migrations/20250520110310_AddIndexForOuterId.cs
src/VirtoCommerce.InventoryModule.Data.PostgreSql/Migrations/InventoryDbContextModelSnapshot.cs
src/VirtoCommerce.InventoryModule.Data.PostgreSql/VirtoCommerce.InventoryModule.Data.PostgreSql.csproj
src/VirtoCommerce.InventoryModule.Data.SqlServer/Migrations/20250520110239_AddIndexForOuterId.Designer.cs
src/VirtoCommerce.InventoryModule.Data.SqlServer/Migrations/20250520110239_AddIndexForOuterId.cs
src/VirtoCommerce.InventoryModule.Data.SqlServer/Migrations/InventoryDbContextModelSnapshot.cs
src/VirtoCommerce.InventoryModule.Data.SqlServer/VirtoCommerce.InventoryModule.Data.SqlServer.csproj
src/VirtoCommerce.InventoryModule.Data/Model/InventoryEntity.cs
src/VirtoCommerce.InventoryModule.Data/Repositories/InventoryDbContext.cs
src/VirtoCommerce.InventoryModule.Data/Services/FulfillmentCenterService.cs
src/VirtoCommerce.InventoryModule.Data/VirtoCommerce.InventoryModule.Data.csproj
src/VirtoCommerce.InventoryModule.Web/Controllers/Api/InventoryModuleController.cs
src/VirtoCommerce.InventoryModule.Web/module.manifest

GET /api/inventory/fulfillmentcenters/outer/{outerId}
https://virtocommerce.atlassian.net/browse/VCST-3154
https://vc3prerelease.blob.core.windows.net/packages/VirtoCommerce.Inventory_3.810.0-pr-149-4c66.zip

VCST-3154: Extend Rest API with GetByOuterId
